### ISSUE TITLE
KeyError: bufnr

### ISSUE THREAD

**Issue by petobens** [raghur/fruzzy#11]
Consider the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/raghur/fruzzy
filetype plugin indent on

call denite#custom#source('_', 'matchers', ['matcher/fruzzy'])

function! s:DeniteScanDir()
    let narrow_dir = input('Input narrowing directory: ', '', 'file')
    if narrow_dir == ''
        return
    endif
    call denite#start([{'name': 'file/rec', 'args': [narrow_dir]}])
endfunction

nnoremap <silent> ,sd :call <SID>DeniteScanDir()<CR>
```

If I now type `,sd` and then use `.` as narrowing dir then I get the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 121, in _start
[denite]     self.update_candidates()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 312, in update_candidates
[denite]     self._denite.filter_candidates(self._context)):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 120, in filter_candidates
[denite]     self.match_candidates(ctx, matchers)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 159, in match_candidates
[denite]     context['candidates'] = self.call_matchers(ctx, matchers)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 163, in call_matchers
[denite]     ctx['candidates'] = matcher.filter(ctx)
[denite]   File "/home/pedro/.config/nvim/bundle/repos/github.com/raghur/fruzzy/rplugin/python3/denite/filter/matcher/fruzzymatcher.py", line 55, in filter
[denite]     buffer = context['bufnr']
[denite] KeyError: 'bufnr'
[denite] Please execute :messages command.
```
BTW: Thanks for this awesome matcher.

**Comment by Shougo** [comment]
Reproduced.  It is denite.nvims error.  I will fix it later.

**Comment by Shougo** [comment]
I have fixed the error in denite.nvim.
Please update it to the latest version.

**Comment by petobens** [comment]
Thanks @Shougo this is indeed fix now. One minor question, what's the  dein equivalent for:
```
Plug 'raghur/fruzzy', {'do': { -> fruzzy#install()}}
```
? 
Should this be done with build? 
```
call dein#add('raghur/fruzzy', {'build': ...)
```

Maybe we could update the README with these instructions @raghur? Feel free to close after this. Thanks to both of you

**Comment by Shougo** [comment]
You should use hook_post_update instead.

**Comment by petobens** [comment]
> You should use hook_post_update instead.
@Shougo when using
```
call dein#add('raghur/fruzzy', {'hook_post_update': 'call fruzzy#install()'})
```
I still get the following message:
```
[denite] Native module requested but module was not found
[denite] falling back to python implementation
[denite] execute :call fruzzy#install() to install the native module
[denite] and then check if you have fruzzy_mod.so or fruzzy_mod.pyd at /home/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3
```
(which apparently means that `fruzzy#install()` was not called). Is this a bug or am i using it wrongly?

**Comment by Shougo** [comment]
> I still get the following message:

Because, it is executed it is updated correctly.
I think fruzzy is not updated when you executed.

> (which apparently means that fruzzy#install() was not called). Is this a bug or am i using it wrongly?

So this is intended behavior.

**Comment by raghur** [comment]
1. did you restart vim/nvim after installation? (Only required if you've already launched denite before updating/installing plugins)
2. Is the .so/.pyd present at /home/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3?
3. What's your os and are you running vim or nvim?

**Comment by raghur** [comment]
you can also just `:call fruzzy#install` to see if it's working. It should print out some messages abt the installation.

**Comment by petobens** [comment]
> you can also just :call fruzzy#install

Thanks @raghur I do know that I can do this but I actually want to avoid doing it and want the plugin manager to handle it. 

> I think fruzzy is not updated when you executed.

@Shougo I don't get if this is an issue with dein or fruzzy. Basically I want to avoid having to run `:call fruzzy#install()` manually and would like dein to handle it the first time (as apparently `vim-plug` does with `do` command).

**Comment by raghur** [comment]
What I meant is to call it manually to check that it installs without error. If it does, then you can show that to @Shougo for further support with dein.

**Comment by petobens** [comment]
It does work when calling it manually:
```
fruzzy: downloading https://github.com/raghur/fruzzy/releases/download/v0.4/fruzzy_mod.so to fruzzy_mod.so
native mod /home/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/fruzzy_mod.so installed - restart vim/nvim if needed
```
but it doesn't seem to work with dein.

**Comment by Shougo** [comment]
@petobens Please test the latest dein.vim.  I have fixed post_update behavior.

**Comment by petobens** [comment]
@Shougo With the latest version I'm getting the following error:
```
[dein] Not installed plugins: ['fruzzy']
[dein] Update started: (2018/10/20 09:38:36)[dein] Updated plugins:
[dein]   fruzzy(1 change)
[dein] Error occurred while executing hook: fruzzy
[dein] Vim(call):E117: Unknown function: fruzzy#install
[dein] Done: (2018/10/20 09:38:38)Press ENTER or type command to continue
```
when using:
```vim
    call dein#add('raghur/fruzzy',
        \{'hook_post_update': 'call fruzzy#install()'})
```

**Comment by Shougo** [comment]
OK.  I get it.  I have fixed the problem.
Please update dein.vim again.

**Comment by petobens** [comment]
It's working now. Thanks!!
